# Render.yaml
services:
  - type: web
    name: brain-tumor-classifier
    runtime: python
    pythonVersion: "3.8.16"  # Explicit version
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
