services:
  - type: web
    name: brain-tumor-classifier
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production